### PR TITLE
Packaging improvements, Use pytest fixtures, Support Python3.11

### PR DESCRIPTION
**Pull request by Zeitsperre**
Hi,

I was looking at what your package needed in order to support Python3.11, and I realized there were a few things that could be improved. There's a lot going on here, so here's a summary:

### Changes

* Added package classifiers to better describe pysheds on PyPI, including support on Python3.11.
* Added installer recipes (`pysheds[dev]` and `pysheds[recipes]`), to install the necessary packages for running tests and notebooks, respectively.
* Removed several bare exceptions. Now using `ModuleNotFound` and `ImportError` where appropriate.
* Update GitHub Actions to their newest version and package-building workflow to support Python3.11 builds

I was having issues with pytest segfaulting as well, so l I also made some significant changes to how `pytest` tests are configured and run.

Previously, the expectation was that tests are run in sequence, with some tests mutating a base class used further down. This design made it so that all tests are co-dependent, going against that design principles of `pytest`.

The approach I've done here is to create a few base objects that are instantiated on every test run when they are called (not ideal and can very likely probably be optimized). What this does is make it so that test failures in some tests should not impact subsequent tests. For tests that create temporary files, I've applied the `tmp_path` fixture so that they do not create artifacts that need to be removed by the user.

My impression from all these changes is that `pytest` is **much** quicker to load and no longer segfaults on my local machine.

For more information about `pytest` fixtures: https://docs.pytest.org/en/7.1.x/explanation/fixtures.html#about-fixtures

I didn't want to go overboard, but if you would appreciate further changes, such as more uniform [numpy-docstring conventions](https://numpydoc.readthedocs.io/en/latest/format.html), I don't mind continuing with this work in this PR or in another.

If you'd like any clarifications, please let me know.

Best,

### CODE REVIEW

**Comment by mdbartos** [comment]
Thanks for taking the time to write this PR @Zeitsperre. I am not quite sure why the tests are not running with GitHub actions in this PR. Any idea why?

**Comment by mdbartos** [comment]
Ok, that last commit seemed to do it.

**Comment by Zeitsperre** [comment]
Great! I'll fix my merge conflicts tomorrow (I'm still _technically_ on vacation). Best!

**Comment by mdbartos** [comment]
Hi @Zeitsperre, can you update your summary to reflect the commits added after the PR was initiated? Thanks.

**Comment by mdbartos** [comment]
Quick request: can you change the version number in pysheds/__init__.py to 0.3.4?

Thanks,
MDB

**Comment by mdbartos** [comment]
Also, I think the status badges on the readme are outdated. If you could fix with this PR, it would be much appreciated.

**Comment by Zeitsperre** [comment]
Badge is fixed and the version number seems to be already at v0.3.4!

For the install recipes, I went with `dev` and `recipes` (to reflect the requirements needed to run the notebooks under "recipes"). Are these names to your liking?

**Comment by mdbartos** [comment]
Looks good to me! Ready to merge when you give the go-ahead.

**Comment by Zeitsperre** [comment]
Great! Yes, LGTM!

**Review by mdbartos — APPROVED** [review]

**Pull request merged**
